import type {
  PreferenceDefinition,
  PreferenceValue,
  SettingsCategoryId,
} from "./types"

function pref(
  partial: Omit<PreferenceDefinition, "scope" | "kind" | "keywords"> & {
    keywords?: string[]
    scope?: PreferenceDefinition["scope"]
    kind?: PreferenceDefinition["kind"]
    availability?: PreferenceDefinition["availability"]
  }
): PreferenceDefinition {
  return {
    scope: partial.scope ?? "user",
    kind: partial.kind ?? "preference",
    keywords: partial.keywords ?? [],
    availability: partial.availability ?? "available",
    ...partial,
  }
}

/**
 * PreferenceRegistry — single source of truth for every setting.
 * No hardcoded settings in UI components.
 */
export const PREFERENCE_REGISTRY: PreferenceDefinition[] = [
  // ——— General ———
  pref({
    id: "general.language",
    category: "general",
    section: "Region",
    label: "Language",
    control: "select",
    defaultValue: "en-GB",
    options: [
      { value: "en-GB", label: "English (UK)" },
      { value: "en-US", label: "English (US)" },
    ],
    keywords: ["locale", "english"],
  }),
  pref({
    id: "general.timezone",
    category: "general",
    section: "Region",
    label: "Time zone",
    control: "select",
    defaultValue: "Europe/London",
    options: [
      { value: "Europe/London", label: "Europe/London" },
      { value: "UTC", label: "UTC" },
      { value: "America/New_York", label: "America/New York" },
      { value: "America/Los_Angeles", label: "America/Los Angeles" },
      { value: "Australia/Sydney", label: "Australia/Sydney" },
    ],
    keywords: ["timezone", "tz"],
  }),
  pref({
    id: "general.units",
    category: "general",
    section: "Units",
    label: "Units",
    control: "select",
    defaultValue: "imperial",
    options: [
      { value: "metric", label: "Metric" },
      { value: "imperial", label: "Imperial" },
    ],
    keywords: ["metric", "imperial", "kg", "lb", "measurement"],
  }),
  pref({
    id: "general.date_format",
    category: "general",
    section: "Calendar",
    label: "Date format",
    control: "select",
    defaultValue: "dd/MM/yyyy",
    options: [
      { value: "dd/MM/yyyy", label: "DD/MM/YYYY" },
      { value: "MM/dd/yyyy", label: "MM/DD/YYYY" },
      { value: "yyyy-MM-dd", label: "YYYY-MM-DD" },
    ],
    keywords: ["date", "format"],
  }),
  pref({
    id: "general.first_day_of_week",
    category: "general",
    section: "Calendar",
    label: "First day of week",
    control: "select",
    defaultValue: "monday",
    options: [
      { value: "monday", label: "Monday" },
      { value: "sunday", label: "Sunday" },
    ],
    keywords: ["week", "calendar", "monday", "sunday"],
  }),

  // ——— Profile ———
  pref({
    id: "profile.photo",
    category: "profile",
    section: "Identity",
    label: "Profile photo",
    description: "Coming soon — photo upload will land with account sync.",
    control: "action",
    defaultValue: null,
    kind: "action",
    actionId: "profile.photo",
    availability: "coming_soon",
    keywords: ["avatar", "picture", "image"],
  }),
  pref({
    id: "profile.name",
    category: "profile",
    section: "Identity",
    label: "Name",
    control: "text",
    defaultValue: "",
    keywords: ["full name"],
  }),
  pref({
    id: "profile.preferred_name",
    category: "profile",
    section: "Identity",
    label: "Preferred name",
    control: "text",
    defaultValue: "",
    keywords: ["nickname", "display name"],
  }),
  pref({
    id: "profile.email",
    category: "profile",
    section: "Identity",
    label: "Email",
    control: "email",
    defaultValue: "",
    keywords: ["email", "contact"],
  }),
  pref({
    id: "profile.date_of_birth",
    category: "profile",
    section: "Body",
    label: "Date of birth",
    control: "date",
    defaultValue: "",
    keywords: ["dob", "birthday", "age"],
  }),
  pref({
    id: "profile.sex",
    category: "profile",
    section: "Body",
    label: "Sex",
    control: "select",
    defaultValue: "male",
    options: [
      { value: "male", label: "Male" },
      { value: "female", label: "Female" },
      { value: "other", label: "Other" },
      { value: "prefer_not", label: "Prefer not to say" },
    ],
    keywords: ["gender", "sex"],
  }),
  pref({
    id: "profile.height",
    category: "profile",
    section: "Body",
    label: "Height",
    control: "number",
    defaultValue: null,
    unit: "cm",
    keywords: ["height", "stature"],
  }),
  pref({
    id: "profile.current_weight",
    category: "profile",
    section: "Body",
    label: "Current weight",
    description: "Optional override — Progress still prefers Apple Health weight.",
    control: "number",
    defaultValue: null,
    unit: "lb",
    keywords: ["weight", "body mass"],
  }),

  // ——— Health profile ———
  pref({
    id: "health.conditions",
    category: "health_profile",
    section: "Clinical",
    label: "Medical conditions",
    control: "textarea",
    defaultValue: "",
    keywords: ["diagnosis", "condition", "illness"],
  }),
  pref({
    id: "health.allergies",
    category: "health_profile",
    section: "Clinical",
    label: "Allergies",
    control: "textarea",
    defaultValue: "",
    keywords: ["allergy", "reaction"],
  }),
  pref({
    id: "health.smoking",
    category: "health_profile",
    section: "Lifestyle",
    label: "Smoking status",
    control: "select",
    defaultValue: "never",
    options: [
      { value: "never", label: "Never" },
      { value: "former", label: "Former" },
      { value: "current", label: "Current" },
    ],
    keywords: ["smoke", "tobacco"],
  }),
  pref({
    id: "health.alcohol",
    category: "health_profile",
    section: "Lifestyle",
    label: "Alcohol consumption",
    control: "select",
    defaultValue: "moderate",
    options: [
      { value: "none", label: "None" },
      { value: "light", label: "Light" },
      { value: "moderate", label: "Moderate" },
      { value: "heavy", label: "Heavy" },
    ],
    keywords: ["alcohol", "drinking"],
  }),
  pref({
    id: "health.exercise_level",
    category: "health_profile",
    section: "Lifestyle",
    label: "Exercise level",
    control: "select",
    defaultValue: "moderate",
    options: [
      { value: "sedentary", label: "Sedentary" },
      { value: "light", label: "Light" },
      { value: "moderate", label: "Moderate" },
      { value: "high", label: "High" },
      { value: "athlete", label: "Athlete" },
    ],
    keywords: ["exercise", "activity", "training"],
  }),
  pref({
    id: "health.diet",
    category: "health_profile",
    section: "Lifestyle",
    label: "Diet preference",
    control: "select",
    defaultValue: "omnivore",
    options: [
      { value: "omnivore", label: "Omnivore" },
      { value: "vegetarian", label: "Vegetarian" },
      { value: "vegan", label: "Vegan" },
      { value: "keto", label: "Keto" },
      { value: "other", label: "Other" },
    ],
    keywords: ["diet", "food", "eating"],
  }),
  pref({
    id: "health.blood_type",
    category: "health_profile",
    section: "Clinical",
    label: "Blood type",
    control: "select",
    defaultValue: "unknown",
    options: [
      { value: "unknown", label: "Unknown" },
      { value: "O+", label: "O+" },
      { value: "O-", label: "O-" },
      { value: "A+", label: "A+" },
      { value: "A-", label: "A-" },
      { value: "B+", label: "B+" },
      { value: "B-", label: "B-" },
      { value: "AB+", label: "AB+" },
      { value: "AB-", label: "AB-" },
    ],
    keywords: ["blood type", "abo"],
  }),
  pref({
    id: "health.primary_care",
    category: "health_profile",
    section: "Contacts",
    label: "Primary care provider",
    control: "text",
    defaultValue: "",
    keywords: ["gp", "doctor", "physician"],
  }),
  pref({
    id: "health.emergency_contact",
    category: "health_profile",
    section: "Contacts",
    label: "Emergency contact",
    control: "text",
    defaultValue: "",
    keywords: ["emergency", "next of kin"],
  }),

  // ——— Goals ———
  pref({
    id: "goals.weight",
    category: "goals",
    section: "Body composition",
    label: "Goal weight",
    control: "number",
    defaultValue: 220,
    unit: "lb",
    keywords: ["weight", "target weight", "goal weight"],
  }),
  pref({
    id: "goals.body_fat",
    category: "goals",
    section: "Body composition",
    label: "Target body fat",
    control: "number",
    defaultValue: 25,
    unit: "%",
    keywords: ["body fat", "bf%", "composition"],
  }),
  pref({
    id: "goals.muscle_mass",
    category: "goals",
    section: "Body composition",
    label: "Target muscle mass",
    control: "number",
    defaultValue: null,
    unit: "lb",
    keywords: ["muscle", "lean mass"],
  }),
  pref({
    id: "goals.waist",
    category: "goals",
    section: "Body composition",
    label: "Target waist",
    control: "number",
    defaultValue: null,
    unit: "cm",
    keywords: ["waist", "circumference"],
  }),
  pref({
    id: "goals.sleep",
    category: "goals",
    section: "Recovery",
    label: "Target sleep",
    control: "number",
    defaultValue: 7.5,
    unit: "h",
    step: 0.25,
    keywords: ["sleep", "rest"],
  }),
  pref({
    id: "goals.protein",
    category: "goals",
    section: "Nutrition",
    label: "Target protein",
    control: "number",
    defaultValue: 220,
    unit: "g",
    keywords: ["protein", "macros", "nutrition"],
  }),
  pref({
    id: "goals.calories",
    category: "goals",
    section: "Nutrition",
    label: "Target calories",
    control: "number",
    defaultValue: 2200,
    unit: "kcal",
    keywords: ["calories", "kcal", "energy", "nutrition"],
  }),
  pref({
    id: "goals.water",
    category: "goals",
    section: "Nutrition",
    label: "Target water",
    control: "number",
    defaultValue: 3.5,
    unit: "L",
    step: 0.1,
    keywords: ["water", "hydration"],
  }),
  pref({
    id: "goals.steps",
    category: "goals",
    section: "Activity",
    label: "Target steps",
    control: "number",
    defaultValue: 10000,
    keywords: ["steps", "walking"],
  }),
  pref({
    id: "goals.workouts",
    category: "goals",
    section: "Activity",
    label: "Target workouts",
    control: "number",
    defaultValue: 4,
    unit: "/week",
    keywords: ["workouts", "training", "gym"],
  }),
  pref({
    id: "goals.weight_loss_rate",
    category: "goals",
    section: "Body composition",
    label: "Preferred rate of weight loss",
    control: "number",
    defaultValue: 1,
    unit: "lb/week",
    step: 0.1,
    keywords: ["rate", "deficit", "loss pace"],
  }),

  // ——— Treatments ———
  pref({
    id: "treatments.prescription_lead_time",
    category: "treatments",
    section: "Defaults",
    label: "Default prescription lead time",
    control: "number",
    defaultValue: 7,
    unit: "days",
    keywords: ["prescription", "repeat", "lead time"],
  }),
  pref({
    id: "treatments.peptide_discard",
    category: "treatments",
    section: "Defaults",
    label: "Default peptide discard period",
    control: "number",
    defaultValue: 28,
    unit: "days",
    keywords: ["peptide", "discard", "vial"],
  }),
  pref({
    id: "treatments.freezer_reminder",
    category: "treatments",
    section: "Reminders",
    label: "Default freezer reminder",
    control: "toggle",
    defaultValue: true,
    keywords: ["freezer", "storage"],
  }),
  pref({
    id: "treatments.fridge_reminder",
    category: "treatments",
    section: "Reminders",
    label: "Default fridge reminder",
    control: "toggle",
    defaultValue: true,
    keywords: ["fridge", "storage"],
  }),
  pref({
    id: "treatments.inventory_threshold",
    category: "treatments",
    section: "Inventory",
    label: "Inventory warning threshold",
    control: "number",
    defaultValue: 7,
    unit: "days",
    keywords: ["inventory", "supply", "warning"],
  }),
  pref({
    id: "treatments.injection_reminders",
    category: "treatments",
    section: "Reminders",
    label: "Injection reminder preferences",
    control: "select",
    defaultValue: "scheduled",
    options: [
      { value: "off", label: "Off" },
      { value: "scheduled", label: "At scheduled time" },
      { value: "morning", label: "Morning summary" },
    ],
    keywords: ["injection", "dose reminder", "medication"],
  }),

  // ——— Notifications ———
  pref({
    id: "notifications.weight",
    category: "notifications",
    section: "Health",
    label: "Weight reminders",
    control: "toggle",
    defaultValue: false,
    keywords: ["weight", "reminder"],
  }),
  pref({
    id: "notifications.medication",
    category: "notifications",
    section: "Health",
    label: "Medication reminders",
    control: "toggle",
    defaultValue: true,
    keywords: ["medication", "dose", "reminder"],
  }),
  pref({
    id: "notifications.prescription",
    category: "notifications",
    section: "Health",
    label: "Prescription reminders",
    control: "toggle",
    defaultValue: true,
    keywords: ["prescription", "repeat"],
  }),
  pref({
    id: "notifications.treatment",
    category: "notifications",
    section: "Health",
    label: "Treatment reminders",
    control: "toggle",
    defaultValue: true,
    keywords: ["treatment", "peptide"],
  }),
  pref({
    id: "notifications.blood",
    category: "notifications",
    section: "Health",
    label: "Blood test reminders",
    control: "toggle",
    defaultValue: true,
    keywords: ["blood", "lab", "test"],
  }),
  pref({
    id: "notifications.goals",
    category: "notifications",
    section: "Health",
    label: "Goal reminders",
    control: "toggle",
    defaultValue: false,
    keywords: ["goals", "targets"],
  }),
  pref({
    id: "notifications.weekly_report",
    category: "notifications",
    section: "Reports",
    label: "Weekly report",
    control: "toggle",
    defaultValue: true,
    keywords: ["weekly", "report"],
  }),
  pref({
    id: "notifications.monthly_report",
    category: "notifications",
    section: "Reports",
    label: "Monthly report",
    control: "toggle",
    defaultValue: true,
    keywords: ["monthly", "report"],
  }),
  pref({
    id: "notifications.desktop",
    category: "notifications",
    section: "Channels",
    label: "Desktop notifications",
    control: "toggle",
    defaultValue: false,
    keywords: ["desktop", "browser"],
  }),
  pref({
    id: "notifications.email",
    category: "notifications",
    section: "Channels",
    label: "Email notifications",
    control: "toggle",
    defaultValue: false,
    keywords: ["email"],
  }),
  pref({
    id: "notifications.push",
    category: "notifications",
    section: "Channels",
    label: "Push notifications",
    description: "Mobile push arrives with the Geoffit app.",
    control: "toggle",
    defaultValue: false,
    availability: "coming_soon",
    keywords: ["push", "mobile"],
  }),

  // ——— Privacy ———
  pref({
    id: "privacy.password",
    category: "privacy",
    section: "Account",
    label: "Password",
    control: "action",
    defaultValue: null,
    kind: "action",
    actionId: "privacy.password",
    availability: "coming_soon",
    keywords: ["password", "login"],
  }),
  pref({
    id: "privacy.2fa",
    category: "privacy",
    section: "Account",
    label: "Two-factor authentication",
    control: "action",
    defaultValue: null,
    kind: "action",
    actionId: "privacy.2fa",
    availability: "coming_soon",
    keywords: ["2fa", "mfa", "security"],
  }),
  pref({
    id: "privacy.sessions",
    category: "privacy",
    section: "Sessions",
    label: "Active sessions",
    control: "action",
    defaultValue: null,
    kind: "action",
    actionId: "privacy.sessions",
    availability: "coming_soon",
    keywords: ["sessions", "devices"],
  }),
  pref({
    id: "privacy.devices",
    category: "privacy",
    section: "Sessions",
    label: "Connected devices",
    control: "action",
    defaultValue: null,
    kind: "action",
    actionId: "privacy.devices",
    availability: "coming_soon",
    keywords: ["devices"],
  }),
  pref({
    id: "privacy.export",
    category: "privacy",
    section: "Data",
    label: "Export all data",
    control: "action",
    defaultValue: null,
    kind: "action",
    actionId: "privacy.export",
    keywords: ["export", "download", "backup"],
  }),
  pref({
    id: "privacy.delete",
    category: "privacy",
    section: "Data",
    label: "Delete account",
    control: "action",
    defaultValue: null,
    kind: "action",
    actionId: "privacy.delete",
    availability: "coming_soon",
    keywords: ["delete", "account", "erase"],
  }),
  pref({
    id: "privacy.analytics_share",
    category: "privacy",
    section: "Privacy",
    label: "Share anonymous product analytics",
    control: "toggle",
    defaultValue: false,
    keywords: ["privacy", "analytics", "telemetry"],
  }),

  // ——— AI Coach ———
  pref({
    id: "coach.memory",
    category: "ai_coach",
    section: "Memory",
    label: "Conversation memory",
    control: "toggle",
    defaultValue: true,
    keywords: ["memory", "history", "coach"],
  }),
  pref({
    id: "coach.personality",
    category: "ai_coach",
    section: "Style",
    label: "Coach personality",
    control: "select",
    defaultValue: "direct",
    options: [
      { value: "direct", label: "Direct" },
      { value: "supportive", label: "Supportive" },
      { value: "clinical", label: "Clinical" },
    ],
    keywords: ["personality", "tone"],
  }),
  pref({
    id: "coach.style",
    category: "ai_coach",
    section: "Style",
    label: "Coaching style",
    control: "select",
    defaultValue: "evidence",
    options: [
      { value: "evidence", label: "Evidence-based" },
      { value: "performance", label: "Performance" },
      { value: "longevity", label: "Longevity" },
    ],
    keywords: ["style", "coaching"],
  }),
  pref({
    id: "coach.weekly_review",
    category: "ai_coach",
    section: "Automation",
    label: "Automatic weekly review",
    control: "toggle",
    defaultValue: true,
    keywords: ["weekly", "review", "coach"],
  }),
  pref({
    id: "coach.monthly_review",
    category: "ai_coach",
    section: "Automation",
    label: "Automatic monthly review",
    control: "toggle",
    defaultValue: true,
    keywords: ["monthly", "review", "coach"],
  }),
  pref({
    id: "coach.proactive",
    category: "ai_coach",
    section: "Automation",
    label: "Allow proactive recommendations",
    control: "toggle",
    defaultValue: true,
    keywords: ["proactive", "recommendations"],
  }),
  pref({
    id: "coach.trend_notifications",
    category: "ai_coach",
    section: "Automation",
    label: "Allow trend notifications",
    control: "toggle",
    defaultValue: false,
    keywords: ["trends", "alerts"],
  }),
  pref({
    id: "coach.reset_memory",
    category: "ai_coach",
    section: "Memory",
    label: "Reset AI memory",
    control: "action",
    defaultValue: null,
    kind: "action",
    actionId: "coach.reset_memory",
    keywords: ["reset", "clear memory"],
  }),

  // ——— Appearance ———
  pref({
    id: "appearance.accent",
    category: "appearance",
    section: "Colour",
    label: "Accent colour",
    control: "select",
    defaultValue: "purple",
    options: [
      { value: "purple", label: "Purple (default)" },
      { value: "violet", label: "Violet" },
      { value: "emerald", label: "Emerald" },
      { value: "amber", label: "Amber" },
    ],
    keywords: ["accent", "colour", "color", "purple"],
  }),
  pref({
    id: "appearance.theme",
    category: "appearance",
    section: "Theme",
    label: "Theme",
    control: "select",
    defaultValue: "dark",
    options: [
      { value: "dark", label: "Dark" },
      { value: "system", label: "System" },
    ],
    keywords: ["theme", "dark", "light"],
  }),
  pref({
    id: "appearance.density",
    category: "appearance",
    section: "Layout",
    label: "Density",
    control: "select",
    defaultValue: "comfortable",
    options: [
      { value: "comfortable", label: "Comfortable" },
      { value: "compact", label: "Compact" },
    ],
    keywords: ["density", "spacing", "compact"],
  }),
  pref({
    id: "appearance.chart_animations",
    category: "appearance",
    section: "Motion",
    label: "Chart animations",
    control: "toggle",
    defaultValue: true,
    keywords: ["charts", "animation"],
  }),
  pref({
    id: "appearance.reduce_motion",
    category: "appearance",
    section: "Motion",
    label: "Reduce motion",
    control: "toggle",
    defaultValue: false,
    keywords: ["motion", "accessibility", "a11y"],
  }),

  // ——— Advanced (actions / computed shown in custom panel too) ———
  pref({
    id: "advanced.developer_mode",
    category: "advanced",
    section: "Developer",
    label: "Developer mode",
    control: "toggle",
    defaultValue: false,
    keywords: ["developer", "debug"],
  }),
  pref({
    id: "advanced.import_diagnostics",
    category: "advanced",
    section: "Diagnostics",
    label: "Import diagnostics",
    control: "toggle",
    defaultValue: false,
    keywords: ["import", "diagnostics"],
  }),
  pref({
    id: "advanced.analytics_diagnostics",
    category: "advanced",
    section: "Diagnostics",
    label: "Analytics diagnostics",
    control: "toggle",
    defaultValue: false,
    keywords: ["analytics", "diagnostics"],
  }),
  pref({
    id: "advanced.clear_cache",
    category: "advanced",
    section: "Maintenance",
    label: "Clear cache",
    control: "action",
    defaultValue: null,
    kind: "action",
    actionId: "advanced.clear_cache",
    keywords: ["cache", "clear"],
  }),
  pref({
    id: "advanced.rebuild_analytics",
    category: "advanced",
    section: "Maintenance",
    label: "Rebuild analytics",
    control: "action",
    defaultValue: null,
    kind: "action",
    actionId: "advanced.rebuild_analytics",
    keywords: ["rebuild", "analytics", "recompute"],
  }),
]

export function preferencesForCategory(
  category: SettingsCategoryId
): PreferenceDefinition[] {
  return PREFERENCE_REGISTRY.filter((item) => item.category === category)
}

export function getPreference(id: string): PreferenceDefinition | undefined {
  return PREFERENCE_REGISTRY.find((item) => item.id === id)
}

export function defaultPreferenceValues(): Record<string, PreferenceValue> {
  const values: Record<string, PreferenceValue> = {}
  for (const item of PREFERENCE_REGISTRY) {
    if (item.kind === "preference") {
      values[item.id] = item.defaultValue
    }
  }
  return values
}
